### ISSUE TITLE
'CollectionModel' object has no attribute 'timemap_metadatafile'

### ISSUE THREAD

**Issue by QFD-Felix** [oduwsdl/off-topic-memento-toolkit#6]
Hello ODU WS-DL,

After installing the program by "pip install otmt", I have an error said: 'CollectionModel' object has no attribute 'timemap_metadatafile'. Do you know where the problem is? How can I solve the problem?

Thank you so much!

**Comment by shawnmjones** [comment]
Closing as duplicate of #5.
